<?php

namespace ContainerM4GPhHG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KoEfLZ6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KoEfLZ6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KoEfLZ6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'myfun' => ['services', 'App\\Service\\MyfunctionHelper', 'getMyfunctionHelperService', true],
        ], [
            'myfun' => 'App\\Service\\MyfunctionHelper',
        ]);
    }
}
