<?php

namespace ContainerM880Zp2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyfunctionHelperService extends App_KernelProdDebugContainer
{
    /**
     * Gets the public 'App\Service\MyfunctionHelper' shared autowired service.
     *
     * @return \App\Service\MyfunctionHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MyfunctionHelper.php';

        $container->services['App\\Service\\MyfunctionHelper'] = $instance = new \App\Service\MyfunctionHelper();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Service\\MyfunctionHelper', $container));

        return $instance;
    }
}
