<?php

namespace ContainerM880Zp2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTambahstockControllerService extends App_KernelProdDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\TambahstockController' shared autowired service.
     *
     * @return \App\Controller\Admin\TambahstockController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/TambahstockController.php';

        $container->services['App\\Controller\\Admin\\TambahstockController'] = $instance = new \App\Controller\Admin\TambahstockController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\Admin\\TambahstockController', $container));

        return $instance;
    }
}
