<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxd7Shq\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxd7Shq/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerQxd7Shq.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerQxd7Shq\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerQxd7Shq\App_KernelProdDebugContainer([
    'container.build_hash' => 'Qxd7Shq',
    'container.build_id' => '81fe466e',
    'container.build_time' => 1616676534,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxd7Shq');
