<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM880Zp2\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM880Zp2/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerM880Zp2.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerM880Zp2\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerM880Zp2\App_KernelProdDebugContainer([
    'container.build_hash' => 'M880Zp2',
    'container.build_id' => '903ae11e',
    'container.build_time' => 1615471865,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM880Zp2');
