<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9AoO1T5\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9AoO1T5/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container9AoO1T5.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container9AoO1T5\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container9AoO1T5\App_KernelProdContainer([
    'container.build_hash' => '9AoO1T5',
    'container.build_id' => 'b5548fa8',
    'container.build_time' => 1620236896,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9AoO1T5');
