<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNCxJ6ox\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNCxJ6ox/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNCxJ6ox.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNCxJ6ox\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerNCxJ6ox\App_KernelProdContainer([
    'container.build_hash' => 'NCxJ6ox',
    'container.build_id' => '60b4f2ef',
    'container.build_time' => 1617793585,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNCxJ6ox');
