<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMOF4rSf\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMOF4rSf/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerMOF4rSf.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerMOF4rSf\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerMOF4rSf\App_KernelProdContainer([
    'container.build_hash' => 'MOF4rSf',
    'container.build_id' => '2822c66d',
    'container.build_time' => 1620236461,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMOF4rSf');
