<?php

namespace ContainerMOF4rSf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\KurirController::add' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\Admin\\KurirController::reset_password' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\Admin\\PelangganController::reset_password' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\Admin\\PemesananController::pembayaran_transfer' => ['privates', '.service_locator.KoEfLZ6', 'get_ServiceLocator_KoEfLZ6Service', true],
            'App\\Controller\\Admin\\ProfilController::upd_keamanan' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\Kurir\\PemesananController::pembayaran' => ['privates', '.service_locator.KoEfLZ6', 'get_ServiceLocator_KoEfLZ6Service', true],
            'App\\Controller\\Kurir\\ProfilController::upd_keamanan' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\ProfilController::upd_keamanan' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\RegisterController::add' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\SecurityController::login_admin' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController::login_kurir' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController::login_user' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Admin\\KurirController:add' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\Admin\\KurirController:reset_password' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\Admin\\PelangganController:reset_password' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\Admin\\PemesananController:pembayaran_transfer' => ['privates', '.service_locator.KoEfLZ6', 'get_ServiceLocator_KoEfLZ6Service', true],
            'App\\Controller\\Admin\\ProfilController:upd_keamanan' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\Kurir\\PemesananController:pembayaran' => ['privates', '.service_locator.KoEfLZ6', 'get_ServiceLocator_KoEfLZ6Service', true],
            'App\\Controller\\Kurir\\ProfilController:upd_keamanan' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\ProfilController:upd_keamanan' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\RegisterController:add' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\SecurityController:login_admin' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController:login_kurir' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController:login_user' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Admin\\KurirController::add' => '?',
            'App\\Controller\\Admin\\KurirController::reset_password' => '?',
            'App\\Controller\\Admin\\PelangganController::reset_password' => '?',
            'App\\Controller\\Admin\\PemesananController::pembayaran_transfer' => '?',
            'App\\Controller\\Admin\\ProfilController::upd_keamanan' => '?',
            'App\\Controller\\Kurir\\PemesananController::pembayaran' => '?',
            'App\\Controller\\Kurir\\ProfilController::upd_keamanan' => '?',
            'App\\Controller\\ProfilController::upd_keamanan' => '?',
            'App\\Controller\\RegisterController::add' => '?',
            'App\\Controller\\SecurityController::login_admin' => '?',
            'App\\Controller\\SecurityController::login_kurir' => '?',
            'App\\Controller\\SecurityController::login_user' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\KurirController:add' => '?',
            'App\\Controller\\Admin\\KurirController:reset_password' => '?',
            'App\\Controller\\Admin\\PelangganController:reset_password' => '?',
            'App\\Controller\\Admin\\PemesananController:pembayaran_transfer' => '?',
            'App\\Controller\\Admin\\ProfilController:upd_keamanan' => '?',
            'App\\Controller\\Kurir\\PemesananController:pembayaran' => '?',
            'App\\Controller\\Kurir\\ProfilController:upd_keamanan' => '?',
            'App\\Controller\\ProfilController:upd_keamanan' => '?',
            'App\\Controller\\RegisterController:add' => '?',
            'App\\Controller\\SecurityController:login_admin' => '?',
            'App\\Controller\\SecurityController:login_kurir' => '?',
            'App\\Controller\\SecurityController:login_user' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
