<?php

namespace ContainerMOF4rSf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Kurir\DashboardController' shared autowired service.
     *
     * @return \App\Controller\Kurir\DashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Kurir/DashboardController.php';

        $container->services['App\\Controller\\Kurir\\DashboardController'] = $instance = new \App\Controller\Kurir\DashboardController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\Kurir\\DashboardController', $container));

        return $instance;
    }
}
