<?php

namespace ContainerIkbdwLr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Rtt2X1fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Rtt2X1f' shared service.
     *
     * @return \App\Controller\Kurir\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Kurir\\DashboardController::read_notification()": the $post argument is type-hinted with the non-existent class or interface: "App\\Controller\\Kurir\\Request". Did you forget to add a use statement?');
    }
}
