<?php

namespace ContainerIkbdwLr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MjKUDXhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MjKUDXh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MjKUDXh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', '.errored.Rtt2X1f', NULL, 'Cannot determine controller argument for "App\\Controller\\Kurir\\DashboardController::read_notification()": the $post argument is type-hinted with the non-existent class or interface: "App\\Controller\\Kurir\\Request". Did you forget to add a use statement?'],
        ], [
            'post' => '?',
        ]);
    }
}
