<?php

namespace ContainerIkbdwLr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyfunctionHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\MyfunctionHelper' shared autowired service.
     *
     * @return \App\Service\MyfunctionHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MyfunctionHelper.php';

        $container->services['App\\Service\\MyfunctionHelper'] = $instance = new \App\Service\MyfunctionHelper();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Service\\MyfunctionHelper', $container));

        return $instance;
    }
}
