<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOSyKUkZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOSyKUkZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOSyKUkZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOSyKUkZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOSyKUkZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'OSyKUkZ',
    'container.build_id' => '29b377ea',
    'container.build_time' => 1616862799,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOSyKUkZ');
