<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVoaACPZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVoaACPZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVoaACPZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVoaACPZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVoaACPZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'VoaACPZ',
    'container.build_id' => 'b94cc11d',
    'container.build_time' => 1617104988,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVoaACPZ');
