<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM4GPhHG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM4GPhHG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM4GPhHG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM4GPhHG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM4GPhHG\App_KernelDevDebugContainer([
    'container.build_hash' => 'M4GPhHG',
    'container.build_id' => 'bdd24caa',
    'container.build_time' => 1616940607,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM4GPhHG');
