<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TbChat extends \App\Entity\TbChat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'id_chat', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'kd_pemesanan', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'id_users', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'level', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'pesan', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'date_send'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'id_chat', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'kd_pemesanan', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'id_users', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'level', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'pesan', '' . "\0" . 'App\\Entity\\TbChat' . "\0" . 'date_send'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TbChat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdChat(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdChat', []);

        return parent::getIdChat();
    }

    /**
     * {@inheritDoc}
     */
    public function getKdPemesanan(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKdPemesanan', []);

        return parent::getKdPemesanan();
    }

    /**
     * {@inheritDoc}
     */
    public function setKdPemesanan(?string $kd_pemesanan): \App\Entity\TbChat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKdPemesanan', [$kd_pemesanan]);

        return parent::setKdPemesanan($kd_pemesanan);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsers(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsers', []);

        return parent::getIdUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsers(?int $id_users): \App\Entity\TbChat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsers', [$id_users]);

        return parent::setIdUsers($id_users);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', []);

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevel(?string $level): \App\Entity\TbChat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevel', [$level]);

        return parent::setLevel($level);
    }

    /**
     * {@inheritDoc}
     */
    public function getPesan(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPesan', []);

        return parent::getPesan();
    }

    /**
     * {@inheritDoc}
     */
    public function setPesan(?string $pesan): \App\Entity\TbChat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPesan', [$pesan]);

        return parent::setPesan($pesan);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSend(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSend', []);

        return parent::getDateSend();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSend(?\DateTimeInterface $date_send): \App\Entity\TbChat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSend', [$date_send]);

        return parent::setDateSend($date_send);
    }

}
