<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TbCod extends \App\Entity\TbCod implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'id_cod', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'kd_pemesanan', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'nama_bayar', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'jumlah_bayar', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'tanggal_bayar', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'ins', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'upd'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'id_cod', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'kd_pemesanan', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'nama_bayar', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'jumlah_bayar', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'tanggal_bayar', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'ins', '' . "\0" . 'App\\Entity\\TbCod' . "\0" . 'upd'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TbCod $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCod(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCod', []);

        return parent::getIdCod();
    }

    /**
     * {@inheritDoc}
     */
    public function getKdPemesanan(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKdPemesanan', []);

        return parent::getKdPemesanan();
    }

    /**
     * {@inheritDoc}
     */
    public function setKdPemesanan(?string $kd_pemesanan): \App\Entity\TbCod
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKdPemesanan', [$kd_pemesanan]);

        return parent::setKdPemesanan($kd_pemesanan);
    }

    /**
     * {@inheritDoc}
     */
    public function getNamaBayar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNamaBayar', []);

        return parent::getNamaBayar();
    }

    /**
     * {@inheritDoc}
     */
    public function setNamaBayar(?string $nama_bayar): \App\Entity\TbCod
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNamaBayar', [$nama_bayar]);

        return parent::setNamaBayar($nama_bayar);
    }

    /**
     * {@inheritDoc}
     */
    public function getJumlahBayar(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJumlahBayar', []);

        return parent::getJumlahBayar();
    }

    /**
     * {@inheritDoc}
     */
    public function setJumlahBayar(?int $jumlah_bayar): \App\Entity\TbCod
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJumlahBayar', [$jumlah_bayar]);

        return parent::setJumlahBayar($jumlah_bayar);
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalBayar(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalBayar', []);

        return parent::getTanggalBayar();
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalBayar(?\DateTimeInterface $tanggal_bayar): \App\Entity\TbCod
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalBayar', [$tanggal_bayar]);

        return parent::setTanggalBayar($tanggal_bayar);
    }

    /**
     * {@inheritDoc}
     */
    public function getIns(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIns', []);

        return parent::getIns();
    }

    /**
     * {@inheritDoc}
     */
    public function setIns(?\DateTimeInterface $ins): \App\Entity\TbCod
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIns', [$ins]);

        return parent::setIns($ins);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpd(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpd', []);

        return parent::getUpd();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpd(?\DateTimeInterface $upd): \App\Entity\TbCod
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpd', [$upd]);

        return parent::setUpd($upd);
    }

}
